#ifndef _CONFIGFIELDS_H_
#define _CONFIGFIELDS_H_

// PATHS
// STRING
#define PATH_TO_MKISOFS "PATH TO MKISOFS"
#define PATH_TO_CDRECORD "PATH TO CDRECORD"
#define PATH_TO_READCD "PATH TO READCD"
#define PATH_TO_CDDA2WAV "PATH TO CDDA2WAV"
#define PATH_TO_MKBFS "PATH TO MKBFS"
#define PATH_TO_LAST_PROJECT "PATH TO LAST PROJECT"
#define TEMP_PATH "TEMPORARY FILES FOLDER"

// HeliosConfigView
// BOOL
#define BURNPROOF "BURNPROOF"
#define SIMULATION "SIMULATION"
#define FIXATE_DISC "FIXATE"
#define USE_DAO "USE DAO"
#define TWODRIVECOPY "2-DRIVE-COPY"
#define OVERBURNING "ALLOW OVERBURNING"
// INT32
#define WRITINGSPEED "WRITINGSPEED"
#define FIFOBUFFERSIZE "FIFOBUFFERSIZE"

// DeviceConfigView
// BOOL
#define EJECT_WRITER "EJECT-WRITER"
#define EJECT_READER "EJECT-READER"
#define FORCEDERASING "FORCE RW-ERASING"
// INT8
#define WRITERDEVICE "WRITERDEVICENO."
#define READERDEVICE "READERDEVICENO."
#define SHOWALLDEVICES "SHOWALLDEVICES"
#define SCANNINGMETHOD "DEVSCANMETHOD"

// PathConfigView
// STRING
#define TEMPORARY_PATH "TEMPPATH"
#define PROJECT_PATH "PROJECTPATH"
#define DEFIMAGENAME "DEFAULTIMGNAME"
#define DEFMOUNTPOINT "DEFAULTIMAGEMOUNTPOINT"

// ImageConfigView
#define I_PUBLISHER "I-PUBLISHER"
#define I_PREPARER "I-PREPARER"
#define I_APPLICATION "I-APPLICATION"

// FilesystemConfigView
#define F_ISO9660_CB "ISO9660_CB"
#define F_JOLIET_CB "JOLIET_CB"
#define F_RR_CB "RR_CB"
#define F_HFS_CB "HFS_CB"
#define F_UDF_CB "UDF_CB"
#define F_83FN_RB "83FN"
#define F_31FN_RB "31FN"
#define F_37FN_RB "37FN"
#define F_JOLDEF_RB "JOLDEF_RB"
#define F_JOLUNI_RB "JOLUNI_RB"
#define F_RRDEF_RB "RRDEF_RB"
#define F_RRRAT_RB "RRRAT_RB"
#define F_UDFDEF_RB "UDFDEF_RB"
#define F_UDFDVD_RB "UDFDVD_RB"
#define F_MAPPING_CB "MAPPING_CB"
#define F_MAPPING_TC "MAPPING_TC"

// StandardConfigView
#define S_FILESYSTEM "STANDARDFILESYSTEM"
#define S_VOLUMENAME "STANDARDVOLUMENAME"
#define S_CDTYPE "STANDARDCDTYPE"
#define S_PUBLISHER "STANDARDPUBLISHER"
#define S_PREPARER "STANDARDPREPARER"
#define S_APPLICATION "STANDARDAPPLICATION"
#define S_TEMPPATH "STANDARDTEMPPATH"
#define S_PROJECTPATH "STANDARDPROJECTPATH"

// ApplicationConfigView
#define APP_AUTOUPDATE "APP-AUTOUPDATE"
#define APP_TIMEOUT "APP-TIMEOUT"
#define APP_UPDATEFREQUENCY "APP-UPDATEFREQUENCY"
#define APP_TIMEOUTLENGTH "APP-TIMEOUTLENGTH"

// SaveConfigView
#define STREAMING_MODE "STREAMING-MODE"
#define SAVEWHENQUIT "SAVEWHENQUIT"
#define EXITMODE "EXITMODE"
#define INFOBAR_ENABLED "INFOBAR"
#define AUTOUPDATE "AUTOUPD"
#define LANGUAGE_ID "LANG-ID"
#define BUBBLEHELP "BUBBLEHELP"
#define BURNPRIORITY "BURNPRIORITY"

// SoundConfigView
#define BEEPWHENWRITTEN "BEEPIFDONEWRITING"
#define BEEPWHENIMAGE "BEEPIFDONEIMAGE"
#define BEEPWHENERROR "BEEPIFERROR"

// DATA-CD
#define DATACD_FILESYSTEM "DATACD-FS"
#define DATACD_VOLUMENAME "DATACD-VN"
#define DATACD_MULTISESSION "DATACD-MS"

// AUDIO-CD
#define AUDIOCD_WRITECDTEXT "AUDIOCD-CDTEXT"
#define AUDIOCD_SCMS "AUDIOCD-SCMS"
#define AUDIOCD_ALBUMNAME "AUDIOCD-ALBUMNAME"

// BOOTABLE-CD
#define BOOTCD_FILESYSTEM "BOOTCD-FS"
#define BOOTCD_VOLUMENAME "BOOTCD-VN"
#define BOOTCD_FLOPPYIMAGE "BOOTCD-FLOPPYIMAGE"

// CD EXTRA
#define CDEXTRA_WRITECDTEXT "CDEXTRA-CDTEXT"
#define CDEXTRA_ALBUMNAME "CDEXTRA-ALBUMNAME"
#define CDEXTRA_DATAIMAGE "CDEXTRA-DATAIMAGE"
#define CDEXTRA_VOLUMENAME "CDEXTRA-VOLNAME"
#define CDEXTRA_FILESYSTEM "CDEXTRA-FS"

// DATA DVD
#define DVDVIDEO_FILESYSTEM "DATADVD-FS"
#define DVDVIDEO_VOLUMENAME "DATADVD-VN"

// WINDOW POSITIONS AND SIZES
#define MAINWINDOW_RECT "MAINWINDOW-RECT"
#define WINDOW2_RECT "WINDOW2-RECT"
#define WINDOW4_RECT "WINDOW4-RECT"
#define PREFERENCESWINDOW_RECT "PREFSWIN-RECT"
#define CDRECORDLOGWINDOW_RECT "CDRECORDLOGWIN-RECT"
#define MKISOFSLOGWINDOW_RECT "MKISOFSLOGWIN-RECT"
#define AUDIOWINDOW_RECT "AUDIOWINDOW-RECT"

// window4->view4->textcontrol4
#define PATHTOTHEIMAGE "PATHTOTHEIMAGE"

// recent projects list
#define RECENTPROJECTS_LIST "LIST OF RECENT PROJECTS"

// ProtocolWindow Settings
#define CDRECORD_LOGWIN_VISIBLE "SHOWCDRECORDLOGWIN"
#define MKISOFS_LOGWIN_VISIBLE "SHOWMKISOFSLOGWIN"
#define CDRECORD_LOGFILENAME "CDRECORDLOGFILE"
#define MKISOFS_LOGFILENAME "MKISOFSLOGFILE"
#define CDRECORD_LOG "CDRECORD-LOG"
#define MKISOFS_LOG "MKISOFS-LOG"

// Widths of the BColumnListView's columns
// DATA TYPE CD
#define FILENAMECOLUMN_WIDTH "FNAMECOL"
#define SIZECOLUMN_WIDTH "SIZECOL"
// AUDIO TYPE CD
#define TRACKNUMBERCOLUMN_WIDTH "TRACKNOCOL"
#define TRACKNAMECOLUMN_WIDTH "TRACKNACOL"
#define LENGTHCOLUMN_WIDTH "LENGTHCOL"
#define BYTESCOLUMN_WIDTH "BYTESCOL"
#define INDEXCOLUMN_WIDTH "INDEXCOL"
#define CDTEXTCOLUMN_WIDTH "CDTEXTCOL"

// and now the easy way...
#define DATA_CD_LIST_STATE "DATACDSTATE"
#define AUDIO_CD_LIST_STATE "AUDIOCDSTATE"
#define BOOTABLE_CD_LIST_STATE "BOOTCDSTATE"
#define CD_EXTRA_LIST_STATE "CDEXTRASTATE"
#define DVD_VIDEO_LIST_STATE "DVDVIDEOSTATE"

// COLORS
#define BURNING_STATUS_BAR_COLOR "BSBAR_COLOR"		// 0
#define CDSIZE_STATUS_BAR_COLOR "CDSBAR_COLOR"		// 1
#define LOGWIN_BG_COLOR "LOGBG_COLOR"				// 2
#define LOGWIN_FG_COLOR "LOGFG_COLOR"				// 3
#define LISTSELECTION_COLOR "LIST_SEL_COLOR"		// 4
#define LISTBACKGROUND_COLOR "LISTBACKGROUND_COLOR" // 5

// LANGUAGE SETTINGS
#define CURRENT_LANG_TAG "CURRLANGTAG" // 0

#endif
